#!/usr/bin/env node
import { checkMonitor, createMonitor, health, history, listIncidents, listMonitors, openIncident, resolveIncident } from './engine.js'
const tools = [
  { name: 'statuslane_create_monitor', description: 'Create a local HTTP uptime monitor', inputSchema: { type: 'object', properties: { name: { type: 'string' }, url: { type: 'string' }, expectedStatus: { type: 'number' } }, required: ['name', 'url'] } },
  { name: 'statuslane_check_monitor', description: 'Run an immediate uptime check', inputSchema: { type: 'object', properties: { monitorId: { type: 'string' } }, required: ['monitorId'] } },
  { name: 'statuslane_list_monitors', description: 'List local monitors', inputSchema: { type: 'object', properties: {} } },
  { name: 'statuslane_history', description: 'Get monitor check history', inputSchema: { type: 'object', properties: { monitorId: { type: 'string' } }, required: ['monitorId'] } },
  { name: 'statuslane_open_incident', description: 'Open an incident for a monitor', inputSchema: { type: 'object', properties: { monitorId: { type: 'string' }, note: { type: 'string' } }, required: ['monitorId'] } },
  { name: 'statuslane_resolve_incident', description: 'Resolve an incident', inputSchema: { type: 'object', properties: { incidentId: { type: 'string' } }, required: ['incidentId'] } },
]
async function call(name: string, args: Record<string, unknown>) { if (name === 'statuslane_create_monitor') return createMonitor({ name: String(args.name || ''), url: String(args.url || ''), expectedStatus: args.expectedStatus as number | undefined }); if (name === 'statuslane_check_monitor') return checkMonitor(String(args.monitorId)); if (name === 'statuslane_list_monitors') return listMonitors(); if (name === 'statuslane_history') return history(String(args.monitorId)); if (name === 'statuslane_open_incident') return openIncident(String(args.monitorId), typeof args.note === 'string' ? args.note : undefined); if (name === 'statuslane_resolve_incident') return resolveIncident(String(args.incidentId)); throw new Error('Unknown tool') }
let buffer = ''; process.stdin.setEncoding('utf8'); process.stdin.on('data', async (chunk) => { buffer += chunk; const lines = buffer.split('\n'); buffer = lines.pop() || ''; for (const line of lines) { if (!line.trim()) continue; try { const request = JSON.parse(line); let result: unknown; if (request.method === 'initialize') result = { protocolVersion: '2024-11-05', capabilities: { tools: {} }, serverInfo: { name: 'statuslane', version: '0.1.0' } }; else if (request.method === 'tools/list') result = { tools }; else if (request.method === 'tools/call') result = { content: [{ type: 'text', text: JSON.stringify(await call(request.params.name, request.params.arguments || {}), null, 2) }] }; else if (request.method === 'ping') result = health(); else throw new Error('Method not found'); process.stdout.write(JSON.stringify({ jsonrpc: '2.0', id: request.id, result }) + '\n') } catch (error) { process.stdout.write(JSON.stringify({ jsonrpc: '2.0', id: null, error: { code: -32603, message: error instanceof Error ? error.message : 'Invalid request' } }) + '\n') } } })
